### ISSUE TITLE
Possible commands to be implemented

### ISSUE THREAD

**Issue by 9viz** [y0l016/chatserver#3]
Since we decided to implement some commands, we need a list of all the commands that we need to implement.

For starters, I think the following should be implemented.

- [x] ban
- [ ] kick
- [x] nick
- [x] disconnect

**Comment by y0l016** [comment]
These four should definitely be there. now let's think of the special char or something to make the server know that it's a command rather than a message. I prefer the IRC ideology of having a slash before the command

**Comment by y0l016** [comment]
keeping the issue open until we finalize stuff regarding these commands.

**Comment by 9viz** [comment]
I prefer `/` too. We need to send soem kind of feedback, for a lack of a better word, from the server to all the clients saying that a command (such as ban) was invoked by a person. Also commands like ban, kick shouldn't be universal. Only some people (OP) should able to run them.

About the server thingy, check issue #4

**Comment by 9viz** [comment]
I implemented all the commands listed here except `kick` because we decided against it (at least the server's part in the implementation of the commands). Do check #5
